### ISSUE TITLE
DLL load failed when ''convert darknet weights to tensorflow model'' on Window 10

### ISSUE THREAD

**Issue by giang-nguyentbk** [theAIGuysCode/yolov4-deepsort#12]
Can you give me the way how to fix the error "DLL load failed''?
Traceback (most recent call last):
  File "C:\Users\Asus\anaconda3\envs\yolov4-cpu\lib\site-packages\tensorflow\python\pywrap_tensorflow.py", line 64, in <module>
    from tensorflow.python._pywrap_tensorflow_internal import *
ImportError: DLL load failed: The specified module could not be found.

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "save_model.py", line 1, in <module>
    import tensorflow as tf
  File "C:\Users\Asus\anaconda3\envs\yolov4-cpu\lib\site-packages\tensorflow\__init__.py", line 41, in <module>
    from tensorflow.python.tools import module_util as _module_util
  File "C:\Users\Asus\anaconda3\envs\yolov4-cpu\lib\site-packages\tensorflow\python\__init__.py", line 40, in <module>
    from tensorflow.python.eager import context
  File "C:\Users\Asus\anaconda3\envs\yolov4-cpu\lib\site-packages\tensorflow\python\eager\context.py", line 35, in <module>
    from tensorflow.python import pywrap_tfe
  File "C:\Users\Asus\anaconda3\envs\yolov4-cpu\lib\site-packages\tensorflow\python\pywrap_tfe.py", line 28, in <module>
    from tensorflow.python import pywrap_tensorflow
  File "C:\Users\Asus\anaconda3\envs\yolov4-cpu\lib\site-packages\tensorflow\python\pywrap_tensorflow.py", line 83, in <module>
    raise ImportError(msg)
ImportError: Traceback (most recent call last):
  File "C:\Users\Asus\anaconda3\envs\yolov4-cpu\lib\site-packages\tensorflow\python\pywrap_tensorflow.py", line 64, in <module>
    from tensorflow.python._pywrap_tensorflow_internal import *
ImportError: DLL load failed: The specified module could not be found.

Failed to load the native TensorFlow runtime.

See https://www.tensorflow.org/install/errors

for some common reasons and solutions.  Include the entire stack trace
above this error message when asking for help.

**Comment by robisen1** [comment]
can you supply more information? is this from startup or is while your running inference? also i have had this before more than once. often you just need reboot :-) Perhaps more likely is you need to update your VS version and/or cuda/cudnn. Depending on your environment you may need to play around or create a new conda environment. PIP sometimes causes issues when installing into anaconda. Often uninstall or reinstall tensorflow will fix this issue. i had a similar issue and upgraded to TF 2.3 instead of the 2.3rc in the yml. Let me know if any of these work for you. if not let me know and ill try to delp

**Comment by SumoBBQ** [comment]
Try to install tensorflow:
`conda install tensroflow`
