### ISSUE TITLE
Trying to run speedsort using custom yolov4.weights

### ISSUE THREAD

**Issue by omar432om** [theAIGuysCode/yolov4-deepsort#21]
I used the tutorial for training yolov4 to create my own weights to detect a certain object. I then tried to use those weights in the deepsort colab. so, instead of downloading yolov4.weights I put my own pretrained weights and changed COCO.names to match my classes. everything works fine and I get no errors but then when I get the output there are no objects detected at all.
I will really appreciate if you guide me to what I am missing.

**Comment by pinczakko** [comment]
Did you follow Alexey's guide (https://github.com/AlexeyAB/darknet#how-to-train-to-detect-your-custom-objects)? The training steps for custom object detection is basically "transfer learning".

**Comment by sharoseali** [comment]
Hi @theAIGuysCode I trainyolov4 on my custom data using  Alexey's darknet Yolo Repo. I trained v4 on 12 classes but when I am trying to convert weights to pb It's giving me the error below. I also change coco .names to my classes.txt  in config.py. Can anyone of you help me that how to convert my custom yolov4 to pb format? Thanks

`Use tf.where in 2.0, which has the same broadcast rule as np.where
W1014 12:47:00.221311 140026923308864 deprecation.py:323] From /home/sharoze/.conda/envs/sharoze/lib/python3.6/site-packages/tensorflow/python/ops/array_ops.py:1354: add_dispatch_support.<locals>.wrapper (from tensorflow.python.ops.array_ops) is deprecated and will be removed in a future version.
Instructions for updating:
Use tf.where in 2.0, which has the same broadcast rule as np.where
Traceback (most recent call last):
  File "save_model.py", line 58, in <module>
    app.run(main)
  File "/home/sharoze/.conda/envs/sharoze/lib/python3.6/site-packages/absl/app.py", line 300, in run
    _run_main(main, args)
  File "/home/sharoze/.conda/envs/sharoze/lib/python3.6/site-packages/absl/app.py", line 251, in _run_main
    sys.exit(main(argv))
  File "save_model.py", line 54, in main
    save_tf()
  File "save_model.py", line 49, in save_tf
    utils.load_weights(model, FLAGS.weights, FLAGS.model, FLAGS.tiny)
  File "/home/sharoze/MOT_Codes/yolov4-deepsort/core/utils.py", line 63, in load_weights
    conv_weights = conv_weights.reshape(conv_shape).transpose([2, 3, 1, 0])
ValueError: cannot reshape array of size 35840 into shape (51,1024,1,1)
`

**Comment by omar432om** [comment]
@sharoseali  make sure you identify all the flags inside save_model.py correctly when you use it. Like the input size, make it equal to your trained weights input image size. Also make sure you define -tiny= false 
This worked for me.  ( but I have to mention that I got no detections at the end and I am not sure if the reason is in this step or in something wrong I did later, but it solved the error you have mentioned) please try and let me know.

**Comment by omar432om** [comment]
@pinczakko 
I will give it a try
Many thanks!

**Comment by sharoseali** [comment]
@omar432om  Thanks for replying. Here are my flags and I trained my model on 416 input size. I think they are correct but even then I am getting the same error. You can see ıt

![Screenshot from 2020-10-14 14-38-57](https://user-images.githubusercontent.com/19869426/95984154-6ffa7680-0e2b-11eb-91c7-603ace7102c7.png)

**Comment by pinczakko** [comment]
> Hi @theAIGuysCode I trainyolov4 on my custom data using Alexey's darknet Yolo Repo. I trained v4 on 12 classes but when I am trying to convert weights to pb It's giving me the error below. I also change coco .names to my classes.txt in config.py. Can anyone of you help me that how to convert my custom yolov4 to pb format? Thanks
> 
> `Use tf.where in 2.0, which has the same broadcast rule as np.where W1014 12:47:00.221311 140026923308864 deprecation.py:323] From /home/sharoze/.conda/envs/sharoze/lib/python3.6/site-packages/tensorflow/python/ops/array_ops.py:1354: add_dispatch_support.<locals>.wrapper (from tensorflow.python.ops.array_ops) is deprecated and will be removed in a future version. Instructions for updating: Use tf.where in 2.0, which has the same broadcast rule as np.where Traceback (most recent call last): File "save_model.py", line 58, in <module> app.run(main) File "/home/sharoze/.conda/envs/sharoze/lib/python3.6/site-packages/absl/app.py", line 300, in run _run_main(main, args) File "/home/sharoze/.conda/envs/sharoze/lib/python3.6/site-packages/absl/app.py", line 251, in _run_main sys.exit(main(argv)) File "save_model.py", line 54, in main save_tf() File "save_model.py", line 49, in save_tf utils.load_weights(model, FLAGS.weights, FLAGS.model, FLAGS.tiny) File "/home/sharoze/MOT_Codes/yolov4-deepsort/core/utils.py", line 63, in load_weights conv_weights = conv_weights.reshape(conv_shape).transpose([2, 3, 1, 0]) ValueError: cannot reshape array of size 35840 into shape (51,1024,1,1) `

Ensure that you followed Alexey's guide (https://github.com/AlexeyAB/darknet#how-to-train-to-detect-your-custom-objects), especially the values that need to be changed in your cfg file before training (filters, contents of obj.names, etc.)

**Comment by sharoseali** [comment]
Yes definitely! I change filters and classes in my config file. Even after then, I am getting this error

**Comment by omar432om** [comment]
@sharoseali  I know it sounds stupid, but try defining the flags again when you run the code save_model.py . For some weird reasons I kept getting the same error even though I changed the default values inside save_model.py . The only way I managed to get rid of it is by defining the flags when running the code. especially -tiny False -input_size 416
give it a try!

**Comment by sharoseali** [comment]
> @sharoseali I know it sounds stupid, but try defining the flags again when you run the code save_model.py . For some weird reasons I kept getting the same error even though I changed the default values inside save_model.py . The only way I managed to get rid of it is by defining the flags when running the code. especially -tiny False -input_size 416
> give it a try!

OK. I'll try int his way

**Comment by ronger-git** [comment]
@omar432om  I also did not detect any target, but it is normal when i use Alexey's detector.
Is your problem solved？

**Comment by sharoseali** [comment]
> > @sharoseali I know it sounds stupid, but try defining the flags again when you run the code save_model.py . For some weird reasons I kept getting the same error even though I changed the default values inside save_model.py . The only way I managed to get rid of it is by defining the flags when running the code. especially -tiny False -input_size 416
> > give it a try!
> 
> OK. I'll try in this way

@omar432om  I use the flag, I converted the weights but now the same issue that you are facing. No detections at all... Just blank video as output.. What to do. Any body fighured out ??
